### ISSUE TITLE
Collaboration Time

### ISSUE THREAD

**Issue by drh4kor** [therealklanni/hubot-ingress#21]
Hello project maintainers,
I hereby request to be added to the list of collaborators for this project.

I've undertaken the task to collect new badge images (53 total at 128x128) as well as update the list of badges available in badges.coffee.  Over the next few days, I'll be updating our [forked version](https://github.com/drh4kor/hubot-ingress).  Maybe other teams could also use the updates.  

Regards,

--drh4kor

**Comment by therealklanni** [comment]
You have been invited as a collaborator. Thanks!
